const {
  REACT_APP_API_BASE,
  REACT_APP_BACKEND_URL,
  REACT_APP_FRONTEND_URL,
  REACT_APP_WS_URL,
  REACT_APP_NODE_ENV,
  REACT_APP_NEXT_TELEMETRY_DISABLED,
  REACT_APP_ENABLE_SOURCE_MAPS,
  REACT_APP_PORT,
  REACT_APP_TRUST_PROXY,
  REACT_APP_LOG_LEVEL,
  REACT_APP_HEALTHCHECK_PATH,
  REACT_APP_FEATURE_FLAGS,
  REACT_APP_EXPERIMENTS_ENABLED,
} = process.env;

/**
 * PUBLIC_INTERFACE
 * env - Exposes environment configuration for the frontend app.
 */
export const env = {
  API_BASE: REACT_APP_API_BASE || REACT_APP_BACKEND_URL || '',
  BACKEND_URL: REACT_APP_BACKEND_URL || '',
  FRONTEND_URL: REACT_APP_FRONTEND_URL || '',
  WS_URL: REACT_APP_WS_URL || '',
  NODE_ENV: REACT_APP_NODE_ENV || 'development',
  NEXT_TELEMETRY_DISABLED: REACT_APP_NEXT_TELEMETRY_DISABLED || '1',
  ENABLE_SOURCE_MAPS: REACT_APP_ENABLE_SOURCE_MAPS || 'true',
  PORT: REACT_APP_PORT || '3000',
  TRUST_PROXY: REACT_APP_TRUST_PROXY || 'false',
  LOG_LEVEL: REACT_APP_LOG_LEVEL || 'info',
  HEALTHCHECK_PATH: REACT_APP_HEALTHCHECK_PATH || '/healthz',
  FEATURE_FLAGS: REACT_APP_FEATURE_FLAGS || '',
  EXPERIMENTS_ENABLED: REACT_APP_EXPERIMENTS_ENABLED || 'false',
};

/**
 * PUBLIC_INTERFACE
 * useMock - Derived flag to indicate whether to use local mock API based on API_BASE.
 */
export const useMock = !env.API_BASE;
